name: "[release] image : rc"

on:
  push:
    branches:
      - 'images/*/releases/*-rc'

env:
  REGISTRY   : ghcr.io

jobs:
  build-and-push-image:
    name    : Build => Push to ghcr.io
    runs-on : ubuntu-latest
    steps   :
      - name  : env
        env   :
          GITHUB_CONTEXT : ${{ toJson(github) }}
          GITHUB_REF     : ${{ github.ref }}
          REPO_OWNER     : ${{ github.repository_owner }}
          REPO_NAME      : ${{ github.event.repository.name }}
          REGISTRY       : ${{ env.REGISTRY }}
        run   : |
          echo "GITHUB_CONTEXT : $GITHUB_CONTEXT"

          datetime=$(TZ=UTC-9 date +'%Y-%m-%d.%H-%M-%S')
          echo "datetime : $datetime"

          branch="${GITHUB_REF/refs\/heads\//}"
          echo "branch : $$branch"

          image="$(cut -d '/' -f 2 <<< $branch)"
          echo "image : $image"
          
          version_rc="${branch/images\/$image\/releases\//}"
          version="${version_rc}.${datetime}"
          echo "version_rc : $version_rc"
          echo "version    : $version"
          
          repo_owner_lowercase=${REPO_OWNER,,}
          repo_name_lowercase=${REPO_NAME,,}

          image_tag="${REGISTRY}/${repo_owner_lowercase}/${repo_name_lowercase}/${image}:${version}"
          echo "image_tag : $image_tag"

          git_tag="${image}@${version}"
          echo "git_tag : $git_tag"

          echo "IMAGE_NAME=$image"    >> $GITHUB_ENV
          echo "IMAGE_TAG=$image_tag" >> $GITHUB_ENV
          echo "GIT_TAG=$git_tag"     >> $GITHUB_ENV

      - name  : Check tag exists
        env   :
          REPO_OWNER     : ${{ github.repository_owner }}
          REPO_NAME      : ${{ github.event.repository.name }}
        run   : |
          CODE=`curl --write-out '%{http_code}' \
                     --silent \
                     --output /dev/null \
                     --request GET "https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/git/ref/tags/${GIT_TAG}"`
          echo "\n"
          echo "http_code : $CODE"
          if [[ $CODE == "200" ]] 
          then 
            echo "tag '${GIT_TAG}' is already exists."
            exit 9
          fi

      -
        name  : Checkout repository
        uses  : actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name  : Log in to the Container registry
        uses  : docker/login-action@v1
        with  :
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name  : Build and push Docker image
        uses  : docker/build-push-action@v3
        with  :
          context : ./images/${{ env.IMAGE_NAME }}
          # file    : Dockerfile
          platforms: linux/amd64,linux/arm64
          push    : true
          tags    : ${{ env.IMAGE_TAG }}

      - name  : Tag branch
        run   : |
          git tag         ${{ env.GIT_TAG }}
          git push origin ${{ env.GIT_TAG }}
